[book]
authors = ["Mark Veltzer"]
language = "en"
src = "src"
title = "rscontacts - Google Contacts CLI Tool"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/veltzer/rscontacts"
edit-url-template = "https://github.com/veltzer/rscontacts/edit/master/docs/{path}"
